configfile: "config/config.yaml"

rule all:
    input:
        expand(
            "results/{outdir}/{outfile}",
            outdir=config["seq_accessions"]["output_namespace"],
            outfile=config["seq_accessions"]["output_filename"],
        ),
        expand(
            "results/{outdir}/{outfile}",
            outdir=config["nextalign"]["output_namespace"],
            outfile=config["nextalign"]["output_filename"],
        ),
    default_target: True

module get_reference_seqs:
    snakefile:
        github(
            "jsbrittain/snakeshack",
            path="workflows/OxfordPhyloGenetics/modules/get_remote_file/workflow/Snakefile",
            branch="main",
        )
    config:
        config["get_reference_seqs"]

use rule * from get_reference_seqs as get_reference_seqs_*

module get_owid:
    snakefile:
        github(
            "jsbrittain/snakeshack",
            path="workflows/OxfordPhyloGenetics/modules/get_remote_file/workflow/Snakefile",
            branch="main",
        )
    config:
        config["get_owid"]

use rule * from get_owid as get_owid_*

module get_gisaid:
    snakefile:
        github(
            "jsbrittain/snakeshack",
            path="workflows/OxfordPhyloGenetics/modules/get_remote_file/workflow/Snakefile",
            branch="main",
        )
    config:
        config["get_gisaid"]

use rule * from get_gisaid as get_gisaid_*

module get_gisaid_subsampled_seqs:
    snakefile:
        github(
            "jsbrittain/snakeshack",
            path="workflows/OxfordPhyloGenetics/modules/get_remote_file/workflow/Snakefile",
            branch="main",
        )
    config:
        config["get_gisaid_subsampled_seqs"]

use rule * from get_gisaid_subsampled_seqs as get_gisaid_subsampled_seqs_*

module gisaid:
    snakefile:
        github(
            "jsbrittain/snakeshack",
            path="workflows/OxfordPhyloGenetics/modules/gisaid/workflow/Snakefile",
            branch="main",
        )
    config:
        config["gisaid"]

use rule * from gisaid as gisaid_*

module subsample_gis_owid:
    snakefile:
        github(
            "jsbrittain/snakeshack",
            path="workflows/OxfordPhyloGenetics/modules/subsample_gis_owid/workflow/Snakefile",
            branch="main",
        )
    config:
        config["subsample_gis_owid"]

use rule * from subsample_gis_owid as subsample_gisaid_owid_*

module seq_accessions:
    snakefile:
        github(
            "jsbrittain/snakeshack",
            path="workflows/OxfordPhyloGenetics/modules/seq_accessions/workflow/Snakefile",
            branch="main",
        )
    config:
        config["seq_accessions"]

use rule * from seq_accessions as seq_accessions_*

module process_owid_case_data:
    snakefile:
        github(
            "jsbrittain/snakeshack",
            path="workflows/OxfordPhyloGenetics/modules/process_owid_case_data/workflow/Snakefile",
            branch="main",
        )
    config:
        config["process_owid_case_data"]

use rule * from process_owid_case_data as process_owid_case_data_*

module nextclade:
    snakefile:
        github(
            "jsbrittain/snakeshack",
            path="workflows/OxfordPhyloGenetics/modules/nextclade/workflow/Snakefile",
            branch="main",
        )
    config:
        config["nextclade"]

use rule * from nextclade as nextclade_*

module extract_gisaid_by_seq_name:
    snakefile:
        github(
            "jsbrittain/snakeshack",
            path="workflows/OxfordPhyloGenetics/modules/extract_gisaid_by_seq_name/workflow/Snakefile",
            branch="main",
        )
    config:
        config["extract_gisaid_by_seq_name"]

use rule * from extract_gisaid_by_seq_name as extract_gisaid_by_seq_name_*

module extract_nextclade_seq_names:
    snakefile:
        github(
            "jsbrittain/snakeshack",
            path="workflows/OxfordPhyloGenetics/modules/extract_nextclade_seq_names/workflow/Snakefile",
            branch="main",
        )
    config:
        config["extract_nextclade_seq_names"]

use rule * from extract_nextclade_seq_names as extract_nextclade_seq_names_*

module extract_nextclade_sequences:
    snakefile:
        github(
            "jsbrittain/snakeshack",
            path="workflows/OxfordPhyloGenetics/modules/extract_nextclade_sequences/workflow/Snakefile",
            branch="main",
        )
    config:
        config["extract_nextclade_sequences"]

use rule * from extract_nextclade_sequences as extract_nextclade_sequences_*

module add_reference_sequence:
    snakefile:
        github(
            "jsbrittain/snakeshack",
            path="workflows/OxfordPhyloGenetics/modules/add_reference_sequence/workflow/Snakefile",
            branch="main",
        )
    config:
        config["add_reference_sequence"]

use rule * from add_reference_sequence as add_reference_sequence_*

module nextalign:
    snakefile:
        github(
            "jsbrittain/snakeshack",
            path="workflows/OxfordPhyloGenetics/modules/nextalign/workflow/Snakefile",
            branch="main",
        )
    config:
        config["nextalign"]

use rule * from nextalign as nextalign_*
